server:
  port: 8000

spring:
  application:
    name: todo-app
  datasource:
    username: todo
    password: 123123
    url: jdbc:postgresql://localhost:5432/todo
  jpa:
    show-sql: true
  hibernate:
    ddl-auto: update