server:
  port: 8000

spring:
  application:
    name: todo-app
  datasource:
    username: todo
    password: 123123
    url: jdbc:postgresql://localhost:5432/todo
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: update